### ISSUE TITLE
baseball batting no web table for url

### ISSUE THREAD

**Issue by agemcipe** [DHBWMosbachWI/SportsTables#2]
Hello, 

Thanks for publishing the code for scraping the data. I noticed an error when executing the notebook in the baseball directory.

![grafik](https://user-images.githubusercontent.com/9618011/224742334-48592c75-ce30-4751-bdf6-ecf6f9733ecc.png)

It looks like the url does indeed not contain any html table:

https://www.baseball-reference.com/leagues/majors/1980-standard-batting.shtml
![grafik](https://user-images.githubusercontent.com/9618011/224742625-4072bdf2-983b-414c-b048-33bcc82e0a09.png)

**Comment by agemcipe** [comment]
never mind, seems like the data was only temporarily not available. Retrying on another day solved the issue.

**Comment by SvenLang** [comment]
sorry for the late answer. Okay, good that it is now solved. If you have further questions, feel free to contact me.
